# Generated by Django 5.2.1 on 2025-06-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterlevel',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Sensor Data'},
        ),
        migrations.RemoveField(
            model_name='waterlevel',
            name='distance_cm',
        ),
        migrations.AddField(
            model_name='waterlevel',
            name='distance',
            field=models.FloatField(default=0, verbose_name='Jarak (cm)'),
        ),
        migrations.AddField(
            model_name='waterlevel',
            name='ph_value',
            field=models.FloatField(default=7.0, verbose_name='pH'),
        ),
        migrations.AddField(
            model_name='waterlevel',
            name='tds_value',
            field=models.FloatField(default=0.0, verbose_name='TDS (ppm)'),
        ),
    ]
